wandb_version: 1

dropout:
  value: 0.5
epochs:
  value: 4000
learning_rate:
  value: 0.00018266575907563824
n_comp:
  value: 150
num_layers:
  value: 1
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
