wandb_version: 1

dropout:
  value: 0.2
epochs:
  value: 4000
learning_rate:
  value: 0.0024614033588095108
n_comp:
  value: 50
num_layers:
  value: 1
optimizer:
  value: adam
weight_decay:
  value: 5.0e-05
