wandb_version: 1

dropout:
  value: 0.3
epochs:
  value: 2500
learning_rate:
  value: 0.0010290932149240432
n_comp:
  value: 226
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 5.0e-05
