wandb_version: 1

dropout:
  value: 0.3
epochs:
  value: 2500
learning_rate:
  value: 0.0047142626647178635
n_comp:
  value: 377
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 0
