wandb_version: 1

dropout:
  value: 0.1
epochs:
  value: 2500
learning_rate:
  value: 0.003990294783162256
n_comp:
  value: 377
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 5.0e-05
