wandb_version: 1

dropout:
  value: 0.1
epochs:
  value: 2500
learning_rate:
  value: 0.003649830760279007
n_comp:
  value: 377
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
