wandb_version: 1

dropout:
  value: 0.2
epochs:
  value: 2500
learning_rate:
  value: 0.0007479300927459538
n_comp:
  value: 377
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 5.0e-05
