wandb_version: 1

dropout:
  value: 0.2
epochs:
  value: 2500
learning_rate:
  value: 0.00011708571930831027
n_comp:
  value: 377
num_layers:
  value: 1
optimizer:
  value: adam
weight_decay:
  value: 0
