wandb_version: 1

dropout:
  value: 0.2
epochs:
  value: 2500
learning_rate:
  value: 0.0002097061586658338
n_comp:
  value: 226
num_layers:
  value: 1
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
