wandb_version: 1

dropout:
  value: 0.5
epochs:
  value: 2500
learning_rate:
  value: 6.350406745478238e-05
n_comp:
  value: 226
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 5.0e-05
