wandb_version: 1

dropout:
  value: 0.1
epochs:
  value: 2500
learning_rate:
  value: 0.0023581678209965524
n_comp:
  value: 377
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
