wandb_version: 1

dropout:
  value: 0.5
epochs:
  value: 2500
learning_rate:
  value: 0.0010371704560547489
n_comp:
  value: 226
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
