wandb_version: 1

dropout:
  value: 0.1
epochs:
  value: 2500
learning_rate:
  value: 6.282627163999133e-05
n_comp:
  value: 226
num_layers:
  value: 1
optimizer:
  value: adam
weight_decay:
  value: 0
