wandb_version: 1

dropout:
  value: 0.5
epochs:
  value: 2500
learning_rate:
  value: 0.0005495029262441452
n_comp:
  value: 226
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
