wandb_version: 1

dropout:
  value: 0.3
epochs:
  value: 2500
learning_rate:
  value: 6.338028267893288e-05
n_comp:
  value: 377
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 5.0e-05
